spring:
  application:
    name: qian-system
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${ENV:dev}
  # 添加 Nacos 配置导入
  config:
    import: optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:101.34.70.221}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:qian_sys}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:qian_sys_user}
    password: ${MYSQL_PASSWORD:Sys@10202612}
    druid:
      # 连接池配置
      initial-size: ${DRUID_INITIAL_SIZE:5}
      min-idle: ${DRUID_MIN_IDLE:10}
      max-active: ${DRUID_MAX_ACTIVE:20}
      max-wait: ${DRUID_MAX_WAIT:60000}
      # 检测配置
      time-between-eviction-runs-millis: ${DRUID_TIME_BETWEEN_EVICTION:60000}
      min-evictable-idle-time-millis: ${DRUID_MIN_EVICTABLE:300000}
      max-evictable-idle-time-millis: ${DRUID_MAX_EVICTABLE:900000}
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 监控配置
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: ${DRUID_USERNAME:admin}
        login-password: ${DRUID_PASSWORD:123456}
        reset-enable: false
        allow: ${DRUID_ALLOW_IPS:127.0.0.1}
      # 性能优化
      keep-alive: true
      phy-timeout-millis: 30000
      # 慢SQL记录
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:101.34.70.221}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:kzt10202612}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:10000}
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: ${REDIS_MAX_ACTIVE:20}
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: ${REDIS_MAX_WAIT:-1}
          # 连接池中的最大空闲连接
          max-idle: ${REDIS_MAX_IDLE:10}
          # 连接池中的最小空闲连接
          min-idle: ${REDIS_MIN_IDLE:2}
        # 关闭连接前，允许空闲时间（单位：毫秒）
        shutdown-timeout: 5000
      # 开启事务支持
      enable-transaction-support: true
      # 开启键空间通知
      keyspace-events: Ex
      # 设置客户端连接和操作的超时配置
      connect-timeout: 2000
  cloud:
    # 禁用 Spring Cloud 功能
    enabled: false
    nacos:
      # 禁用服务发现
      discovery:
        enabled: false
        register-enabled: false
        auto-register: false
      config:
        # 禁用配置中心
        enabled: false
        import-check:
          enabled: false
        refresh-enabled: false
    # 禁用所有服务注册相关功能
    service-registry:
      auto-registration:
        enabled: false
    loadbalancer:
      enabled: false
    eureka:
      client:
        enabled: false
      instance:
        enabled: false
    # 禁用配置发现
    discovery:
      enabled: false

# Token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: qianBlogSecret
  # 令牌有效期（默认30分钟）
  expireTime: 30

# JWT配置
jwt:
  # JWT加解密使用的密钥
  secret: qianBlogJwtSecret
  # JWT的有效期，单位秒，默认2小时
  expiration: 7200
  # JWT存储的请求头
  header: Authorization
  # JWT负载中拿到开头
  tokenHead: Bearer 

# Feign配置
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

# 服务器配置
server:
  port: ${SERVER_PORT:9091}
  servlet:
    context-path: /${spring.application.name}
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    max-threads: ${TOMCAT_MAX_THREADS:200}
    min-spare-threads: ${TOMCAT_MIN_THREADS:10}
    max-connections: ${TOMCAT_MAX_CONNECTIONS:10000}
    connection-timeout: ${TOMCAT_TIMEOUT:5000}
    accept-count: 100
    max-http-form-post-size: 20MB
    uri-encoding: UTF-8

# MyBatis配置
mybatis:
  # 类型别名包配置
  typeAliasesPackage: com.qian.system.domain.entity
  # Mapper文件位置
  mapperLocations: classpath*:mapper/**/*.xml
  # 配置映射器
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# Commons 配置
commons:
  lang:
    datetime-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd
    time-format: HH:mm:ss

# 线程池配置
thread-pool:
  core-pool-size: ${CORE_POOL_SIZE:10}
  max-pool-size: ${MAX_POOL_SIZE:50}
  queue-capacity: ${QUEUE_CAPACITY:200}
  keep-alive-seconds: ${KEEP_ALIVE_SECONDS:60}
  thread-name-prefix: qian-async-
  # 拒绝策略：ABORT, CALLER_RUNS, DISCARD, DISCARD_OLDEST
  rejection-policy: CALLER_RUNS
  # 应用关闭等待时间（秒）
  shutdown-timeout: 15

# 日志配置
logging:
  level:
    root: ${LOG_LEVEL_ROOT:DEBUG}  # 修改为 DEBUG 级别
    com.alibaba.nacos: DEBUG
    com.alibaba.cloud.nacos: DEBUG
    com.alibaba.nacos.client.config: DEBUG
    com.alibaba.nacos.client.naming: DEBUG
    com.qian.system: DEBUG  # 添加系统模块的调试日志
    com.qian.system.feign: ${LOG_LEVEL_FEIGN:DEBUG}
    com.qian.system.mapper: ${LOG_LEVEL_MAPPER:DEBUG}
    org.springframework: DEBUG  # 添加 Spring 框架的调试日志
    org.springframework.boot: DEBUG  # 添加 Spring Boot 的调试日志
    org.springframework.context: DEBUG  # 添加 Spring 上下文的调试日志
  file:
    path: ${LOG_PATH:./logs}
    name: ${LOG_PATH:./logs}/qian-system/qian-system.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# SpringDoc配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    filter: true
  packages-to-scan: com.qian.system.controller,com.qian.common.controller
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true
  use-management-port: false
  write-pretty: true

# 调试配置
debug: true  # 启用调试模式